/*******************************************************************************
 * Copyright (c) 2012 Committers of lunifera.org - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
package org.lunifera.runtime.component.configuration.manager.tests;

import static org.knowhowlab.osgi.testing.assertions.BundleAssert.assertBundleAvailable;
import static org.knowhowlab.osgi.testing.assertions.ServiceAssert.assertServiceAvailable;

import java.io.IOException;
import java.util.Dictionary;
import java.util.Hashtable;

import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.knowhowlab.osgi.testing.assertions.BundleAssert;
import org.knowhowlab.osgi.testing.assertions.ServiceAssert;
import org.knowhowlab.osgi.testing.utils.ServiceUtils;
import org.lunifera.runtime.component.configuration.manager.service.IConfigurationService;
import org.osgi.framework.BundleContext;
import org.osgi.framework.Constants;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.InvalidSyntaxException;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.cm.ManagedServiceFactory;

public class ConfigurationManagerTest {

	private static final String HELPER_FACTORY_PID = "org.lunifera.runtime.component.configuration.manager.tests.helper";
	private static BundleContext bc;

	@BeforeClass
	public static void init() {
		bc = FrameworkUtil.getBundle(ConfigurationManagerTest.class)
				.getBundleContext();
		ServiceAssert.setDefaultBundleContext(bc);
		BundleAssert.setDefaultBundleContext(bc);

		// register the managed service factory
		Hashtable<String, String> props = new Hashtable<String, String>();
		props.put(Constants.SERVICE_PID, HELPER_FACTORY_PID);
		bc.registerService(ManagedServiceFactory.class,
				new HelperManagedServiceFactory(), props);
	}

	@Before
	public void setup() throws IOException {
		// reset all configurations
		for (Configuration configuration : findFactoryConfigurations(HELPER_FACTORY_PID)) {
			configuration.delete();
		}
	}

	public void ensureNeedBundlesWasInstalled() {

		assertBundleAvailable("Assertions bundle is not available",
				"org.knowhowlab.osgi.testing.assertions");

		assertBundleAvailable("DS bundle is not available",
				"org.eclipse.equinox.ds");

		assertBundleAvailable("Services bundle is not available",
				"org.eclipse.osgi.services");

		assertBundleAvailable("Log bundle is not available",
				"org.eclipse.equinox.log");

		assertBundleAvailable("CM bundle is not available",
				"org.eclipse.equinox.cm");

		assertBundleAvailable("CM Wrapper bundle is not available",
				"org.lunifera.runtime.component.configuration.manager");

		assertBundleAvailable("CM fragment was not installed",
				"org.lunifera.runtime.component.configuration.manager.test.conf");
	}

	@Before
	public void ensureServicesWasRegistered() {

		ensureNeedBundlesWasInstalled();

		// assert CM service is available
		assertServiceAvailable("CM was not available",
				"org.osgi.service.cm.ConfigurationAdmin");

		// assert Log service is available
		assertServiceAvailable("LogService was not available",
				"org.osgi.service.log.LogService");

		// assert CM wrapper is available
		assertServiceAvailable(
				"CM Wrapper was not available",
				"org.lunifera.runtime.component.configuration.manager.service.IConfigurationService");
	}

	@Test
	public void ensurePidWasRegistered() {

		IConfigurationService cms = ServiceUtils.getService(bc,
				IConfigurationService.class);
		Dictionary<String, Object> props = cms
				.getProperties("org.eclipse.equinox.http.jetty.config.test");

		Assert.assertNotNull("PID was not registered properly.", props);
		Assert.assertEquals("PID was not registered properly.", "8088",
				props.get("http.port"));
	}

	@Test
	public void ensureFactoryPidWithDefaultPidWasRegistered() {

		IConfigurationService cms = ServiceUtils.getService(bc,
				IConfigurationService.class);
		Dictionary<String, Object> props = cms.getFactoryProperties(
				"org.eclipse.equinox.http.jetty.config", "");

		Assert.assertNotNull("Factory properties is null", props);

		Assert.assertTrue(props.size() == 3);

		String actual = cms.getFactoryProperty(
				"org.eclipse.equinox.http.jetty.config", "", "http.port");
		Assert.assertEquals("Property was not found in CM store.", "8080",
				actual);
	}

	/**
	 * Tests that the PID is automatically generated.
	 * 
	 * @throws IOException
	 */
	@Test
	public void ensureFactoryPidAutoGenerated() throws IOException {
		IConfigurationService cms = ServiceUtils.getService(bc,
				IConfigurationService.class);

		// initialize factory configuration
		String pid = cms.initializeFactoryConfigurationStore(
				HELPER_FACTORY_PID, "1001", null);

		Configuration[] configs = findFactoryConfigurations(HELPER_FACTORY_PID);
		Assert.assertEquals(1, configs.length);

		// the returned PID is not the passed one
		Assert.assertFalse("1001".equals(configs[0].getProperties().get(
				Constants.SERVICE_PID)));
		Assert.assertEquals(pid,
				configs[0].getProperties().get(Constants.SERVICE_PID));
	}

	/**
	 * Ensures that initializeFactoryConfigurationStore called with the same
	 * externalPid twice does not create a new configuration.
	 * 
	 * @throws IOException
	 */
	@Test
	public void ensureFactoryPidAccessByExternalPid() throws IOException {

		IConfigurationService cms = ServiceUtils.getService(bc,
				IConfigurationService.class);

		// test
		Assert.assertEquals(0, findFactoryConfigurations(HELPER_FACTORY_PID).length);

		// initialize factory configuration
		String pid = cms.initializeFactoryConfigurationStore(
				HELPER_FACTORY_PID, "1001", null);
		Assert.assertEquals(1, findFactoryConfigurations(HELPER_FACTORY_PID).length);

		// access twice
		String pid2 = cms.initializeFactoryConfigurationStore(
				HELPER_FACTORY_PID, "1001", null);

		// the returned PIDs are equal
		Assert.assertEquals(pid, pid2);
		Assert.assertEquals(1, findFactoryConfigurations(HELPER_FACTORY_PID).length);
	}

	/**
	 * Ensures that the externalPid is written into the properties of the
	 * configuration.
	 * 
	 * @throws IOException
	 */
	@Test
	public void ensureExternalPidInProperties() throws IOException {

		IConfigurationService cms = ServiceUtils.getService(bc,
				IConfigurationService.class);

		// initialize factory configuration
		cms.initializeFactoryConfigurationStore(HELPER_FACTORY_PID, "1001",
				null);

		String externalPid = (String) findFactoryConfigurations(HELPER_FACTORY_PID)[0]
				.getProperties().get(IConfigurationService.EXTERNAL_PID);
		Assert.assertEquals("1001", externalPid);
	}

	/**
	 * Looks for all factory configurations for the given factoryPid.
	 * 
	 * @param factoryPid
	 * @return
	 * @throws IOException
	 */
	protected Configuration[] findFactoryConfigurations(String factoryPid) {
		Configuration[] configs = null;
		// As ConfigurationAdmin.getConfiguration creates the configuration if
		// it is not yet there, we check its existence first
		try {
			String filter = "(service.factoryPid=" + factoryPid + ")";

			ConfigurationAdmin admin = ServiceUtils.getService(bc,
					ConfigurationAdmin.class);

			configs = admin.listConfigurations(filter);
		} catch (InvalidSyntaxException e) {
			Assert.fail(e.toString());
		} catch (IOException e) {
			Assert.fail(e.toString());
		}

		return configs != null ? configs : new Configuration[0];
	}
}
